/*
    IT WILL OPEN WEB PAGE IF IT DOES NOT FIND THE WIFI.
    INSIDE THE PORTAL WE CAN CONFIGURE MQTT RELATED CREDENTIALS, SSID AND PASSWORD OF THE ROUTER YOU WANT TO CONNECT.
    IT WILL SET UP TIME ZONE AS INDIA
    IT SET MQTT BROKER AND PORT.
    IT WILL SET CALLBACK FUNCTION FOR MQQT INCOMING MESSAGES
    
 INSIDE VOID LOOP:

    IT WILL TRIE TO CONNECT TO MQTT BROKER.
      IF NOT CONNECTED IT WILL KEEP ON TRYING TO CONNECT TO MQTT BROKER
    AFTER CONNECTING TO MQTT IT WILL SUBSCRIBE TO FEW TOPICS, TO THESE FEW TOPICS ESP NODES WILL SEND SOME DATA.
    IT WILL SEND JSON MESSAGE TO ATMEGA VIA SERIAL, THE JSON MESSAGE CONTAINS AVERAGE VALUES OF WHAT THE ESP NODE SENDS VIA MQTT.
    IT WILL RECEIVE ALERTS AND EVENTS FROM ATMEGA VIA SERIAL. THE MESSAGE FORMAT IS JSON.THIS JSON MESSAGE CONTAINS AT MODE ATMEGA IS RUNNING AND SOME ALERT LEVELS.
    IT WILL RECEIVE MANUL MODE ON AND OFF OF FANS AND COOLING PADS STATUS IN JSON MESSAGE FROM ATMEGA VIA SERIAL.
    IT WILL MAKE A JSON MESSAGE BY READING ALL GLOBAL VARIABLES AND PUBLISH TO MQTT.
    
*/
