/*
 * DATA SENT TO ESP8266 BY AT MEGA
 * RELAY STATUS IN JSON FORMAT
 * EVENTS IN JSON FORMAT
 * 
 * DATA RECEIVED BY ATMEGA FROM ESP8266
 * APP DATA
 * 
 * WHEN THE DEVICE ENTERS INTO SECHUDLE MODE?
 * WELL MEGA WILL ENTER INTO SCHEDULE MODE WHEN checkflag TO checkflag8 any oneof them is TRUE.
 * 
 * 
 * WHEN checkflag WILL BE TRUE?
 * IT WILL BE TRUE WHEN WE SET SLOTS IN DISPLAY.
 * 
 * WHEN CHECKFLAG WILL BE FALSE?
 * NEVER. SO TO MAKE IT FALSE WE NEED TO RESET ATMEGA.
 * 
 * WHEN THE DEVICE ENTERS INTO AUTO MODE?
 * 
 * HOW TO GET OUT OF AUTO MODE?
 * 
 VOID LOOP()
 {
    

    
 }

*/
