# 68008 executable makefile stub for Hello World template project

# RAM or ROM
CODE_LOC = RAM

# no kernel
# USE_KERNEL = 0

# no optimization
OPTIMIZE = 0

# Libraries
LIBS = -lhd44780

include ../../mk/exe.mk
